repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^helm/
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      - id: ruff-format
        name: ruff format
        files: ^src/

      - id: ruff
        name: ruff check
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v10.0.0-rc.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        entry: npm run lint

  - repo: https://github.com/PyCQA/bandit
    rev: 1.9.2
    hooks:
      - id: bandit
        name: bandit security check
        args: ["-c", "pyproject.toml"]
        files: ^src/
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407
    hooks:
      - id: pyright
        name: pyright type-check
        files: ^src/
        pass_filenames: false
        always_run: true
        additional_dependencies:
          [
            "alembic>=1.17.2",
            "asyncpg>=0.31.0",
            "dependency-injector>=4.48.3",
            "fastapi>=0.128.0",
            "htmlmin>=0.1.12",
            "httpx>=0.28.1",
            "jinja2>=3.1.6",
            "psycopg2-binary>=2.9.11",
            "pydantic-settings>=2.12.0",
            "pyjwt>=2.10.1",
            "scalar-fastapi>=1.6.0",
            "slowapi>=0.1.9",
            "uvicorn>=0.40.0",
          ]
