apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "status-page.fullname" . }}-config
  labels:
    {{- include "status-page.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
  ORGANIZATION_NAME: {{ .Values.config.organizationName | quote }}
  THEME: {{ .Values.config.theme | quote }}
  HOST: {{ .Values.config.host | quote }}
  PORT: {{ .Values.config.port | quote }}
  HTTPS: {{ include "status-page.https" . | quote }}
  ADMIN_PATH: {{ .Values.config.adminPath | quote }}
  COOKIE_KEY: {{ .Values.config.cookie.key | quote }}
  JWT_ISSUER: {{ .Values.config.jwt.issuer | quote }}
  JWT_EXPIRES_IN: {{ .Values.config.jwt.expiresIn | quote }}
  JWT_ALGORITHM: {{ .Values.config.jwt.algorithm | quote }}
  POSTGRES_HOST: {{ include "status-page.postgres.host" . | quote }}
  POSTGRES_PORT: {{ include "status-page.postgres.port" . | quote }}
  POSTGRES_DB: {{ include "status-page.postgres.database" . | quote }}
  POSTGRES_USER: {{ include "status-page.postgres.username" . | quote }}
