{{- $needSecret := or (and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret)) (and .Values.postgres.external.enabled (not .Values.postgres.external.existingSecret)) }}
{{- if $needSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-page.fullname" . }}-postgres
  labels:
    {{- include "status-page.labels" . | nindent 4 }}
  {{- if .Values.postgres.enabled }}
  {{- with .Values.postgres.auth.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
type: Opaque
stringData:
  password: {{ if .Values.postgres.enabled }}{{ .Values.postgres.auth.password | required "postgres.auth.password is required when not using existingSecret" }}{{ else }}{{ .Values.postgres.external.password | required "postgres.external.password is required when not using existingSecret" }}{{ end }}
{{- end }}
