{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "status-page.fullname" . }}-secrets
  labels:
    {{- include "status-page.labels" . | nindent 4 }}
  {{- with .Values.secrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  ADMIN_USERNAME: {{ .Values.secrets.adminUsername | required "secrets.adminUsername is required" | quote }}
  ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | required "secrets.adminPassword is required" | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | required "secrets.jwtSecret is required" | quote }}
{{- end }}
