apiVersion: v2
name: status-page
description: A Helm chart for StatusPage application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - status-page
  - monitoring
  - status
  - health
home: https://github.com/goldpulpy/status-page
sources:
  - https://github.com/goldpulpy/status-page
dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
